import Head from 'next/head'

export default function About() {
  return (
    <div>
      <Head>
        <title>Other | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>This is other page</h1>
      </main>
    </div>
  )
}
